entrypoint.filepath = 'source.evl'

std.filepath = 'std/std.evl'

logging.asts.enable = true
logging.asts.log-file = 'output/ast_output.txt'

logging.imports.enable = true
logging.imports.enable-prelude = true
logging.imports.log-file = 'output/import_output.txt'
